CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    google_id VARCHAR(25) UNIQUE,
    facebook_id VARCHAR(25) UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);